# Generated by Django 2.1.3 on 2018-11-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181114_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='email',
            field=models.EmailField(default='test@gmail.edu', max_length=100),
        ),
    ]
